/**
 * Public product -> realm map for the docs sidebar.
 *
 * AUTO-GENERATED by scripts/migration/buildProductRealms.ts. Do not edit by hand.
 * Private/unlaunched products are intentionally excluded so their slugs never
 * ship in a committed artifact. Regenerate with
 * `bun run scripts/migration/buildProductRealms.ts`.
 */

/** Maps a public product id to its realm id. */
export const PRODUCT_REALMS: Record<string, string> = {
  backfeed: "core",
  beacon: "grid",
  eden: "armory",
  fractal: "grid",
  garden: "codex",
  kiln: "grid",
  "life-json": "codex",
  "omni-cli": "armory",
  "omni-terminal": "armory",
  "persona-json": "codex",
  rdk: "reality",
  runa: "core",
  synapse: "grid",
  thornberry: "sigil",
  vortex: "grid",
  zenpetal: "sigil",
};
