/**
 * Emit the committed public product -> realm map used by the docs sidebar.
 *
 * Reads the migration classification (classification.json) and the legacy URL
 * snapshot (legacy-urls.json), intersects with the set of files tracked at git
 * HEAD to determine which pages are PUBLIC (a page is public iff its original,
 * pre-move file is tracked), and writes src/lib/productRealms.generated.ts.
 *
 * A product's realm is the FIRST path segment of its ORIGINAL file under
 * content/docs/ (e.g. content/docs/grid/vortex/index.mdx -> grid). Root-level
 * product files (no realm folder, e.g. content/docs/orin.mdx) have no derivable
 * realm and are intentionally omitted; the sidebar resolves such products to a
 * safe fallback instead.
 *
 * Private/unlaunched products are excluded so their slugs never ship in a
 * committed artifact. Regenerate with `bun run scripts/migration/buildProductRealms.ts`.
 */

import { execFileSync } from "node:child_process";
import { resolve } from "node:path";

import realmsData from "../../realms.json";

interface ClassificationEntry {
  /** Legacy URL. */
  url: string;
  /** Original, pre-move file path under content/docs/. */
  file: string;
  /** Classification kind. */
  kind: string;
  /** New URL, or null. */
  to: string | null;
}

interface LegacyUrlEntry {
  /** Legacy URL. */
  url: string;
  /** Original, pre-move file path under content/docs/. */
  file: string;
}

const dataDir = resolve(import.meta.dir, "data");
const outPath = resolve(
  import.meta.dir,
  "../../src/lib/productRealms.generated.ts",
);

const classification: ClassificationEntry[] = await Bun.file(
  resolve(dataDir, "classification.json"),
).json();
const legacyUrls: LegacyUrlEntry[] = await Bun.file(
  resolve(dataDir, "legacy-urls.json"),
).json();

// Canonical realm ids (the only valid realm values a product may resolve to).
const realmIds = new Set(realmsData.realms.map((r) => r.id));

// Files tracked at git HEAD => the authoritative public set. A page is public
// iff its original pre-move file is tracked; untracked files are private.
const trackedFiles = new Set(
  execFileSync(
    "git",
    ["ls-tree", "-r", "HEAD", "--name-only", "--", "content/docs"],
    { encoding: "utf8" },
  )
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean),
);

// url -> original file, from the legacy snapshot (cross-check for classification).
const fileByUrl = new Map(legacyUrls.map((entry) => [entry.url, entry.file]));

/** Realm of an original file = its first path segment under content/docs/. */
const realmOfFile = (file: string): string | undefined => {
  const [, docs, segment] = file.split("/");
  if (docs !== "docs") return undefined;
  return realmIds.has(segment) ? segment : undefined;
};

/** Product id = second segment of the new URL (/products/<id>/...). */
const productIdFromTo = (to: string): string | undefined => {
  const [, products, id] = to.split("/");
  return products === "products" ? id : undefined;
};

const map: Record<string, string> = {};
const skippedRootLevel: string[] = [];

for (const entry of classification) {
  if (entry.kind !== "product" || !entry.to) continue;

  const file = fileByUrl.get(entry.url) ?? entry.file;
  if (!trackedFiles.has(file)) continue;

  const id = productIdFromTo(entry.to);
  if (!id) continue;

  const realm = realmOfFile(file);
  if (!realm) {
    if (!skippedRootLevel.includes(id)) skippedRootLevel.push(id);
    continue;
  }

  map[id] = realm;
}

const sortedKeys = Object.keys(map).sort((a, b) => a.localeCompare(b));

const body = sortedKeys
  .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(map[id])},`)
  .join("\n");

const output = `/**
 * Public product -> realm map for the docs sidebar.
 *
 * AUTO-GENERATED by scripts/migration/buildProductRealms.ts. Do not edit by hand.
 * Private/unlaunched products are intentionally excluded so their slugs never
 * ship in a committed artifact. Regenerate with
 * \`bun run scripts/migration/buildProductRealms.ts\`.
 */

/** Maps a public product id to its realm id. */
export const PRODUCT_REALMS: Record<string, string> = {
${body}
};
`;

await Bun.write(outPath, output);

// biome-ignore lint/suspicious/noConsole: migration script output
console.info(
  `[product-realms] Wrote ${sortedKeys.length} public product -> realm entries` +
    (skippedRootLevel.length
      ? ` (skipped ${skippedRootLevel.length} root-level product(s) with no realm: ${skippedRootLevel.join(", ")})`
      : ""),
);
