/**
 * Generate the legacy-URL redirect map from the final migration classification.
 *
 * Reads scripts/migration/data/classification.json and legacy-urls.json and
 * emits src/lib/redirects.generated.ts, exporting LEGACY_REDIRECTS: a map from
 * every PUBLIC legacy URL whose canonical location moved to that canonical
 * location. Pure excludes (carbon/ember/quantum/vault) get no entry; ecosystem
 * pages (which do not move) get no entry; the grid/mimic duplicate
 * (redirect-only) is included when public.
 *
 * IMPORTANT: only redirects whose source page is committed at git HEAD are
 * emitted. Private/unlaunched product redirects are intentionally excluded so
 * their slugs never ship in the client bundle (the map is imported by a route
 * and reaches the browser).
 *
 * The map powers `throw redirect(301)` at the edge. Keys are sorted for stable
 * diffs. Do not edit the output by hand; re-run this script instead.
 */

import { execSync } from "node:child_process";
import { resolve } from "node:path";

const dir = import.meta.dir;

type Kind =
  | "product"
  | "realm-hub"
  | "realm-page"
  | "ecosystem"
  | "exclude"
  | "redirect-only";

interface Classified {
  url: string;
  file: string;
  kind: Kind;
  to: string | null;
}

interface LegacyUrl {
  url: string;
  file: string;
}

const classification: Classified[] = await Bun.file(
  resolve(dir, "data/classification.json"),
).json();

const legacyUrls: LegacyUrl[] = await Bun.file(
  resolve(dir, "data/legacy-urls.json"),
).json();

// Public = source page file is tracked at git HEAD. Private/unlaunched product
// pages are untracked, so their slugs must never reach the shipped map. Map
// each committed content file back to its legacy url to build the public set
const publicFiles = new Set(
  execSync("git ls-tree -r HEAD --name-only -- content/docs", {
    cwd: resolve(dir, "../.."),
  })
    .toString()
    .split("\n")
    .filter(Boolean),
);

const publicUrls = new Set(
  legacyUrls.filter((entry) => publicFiles.has(entry.file)).map((e) => e.url),
);

// Kinds whose old URL should 301 to a canonical location when it actually moved
const REDIRECTING_KINDS = new Set<Kind>([
  "product",
  "realm-hub",
  "realm-page",
  "redirect-only",
]);

const redirects: Record<string, string> = {};
for (const page of classification) {
  if (!REDIRECTING_KINDS.has(page.kind)) continue;
  if (page.to === null || page.to === page.url) continue;
  // Skip private/unlaunched sources so their slugs never ship in the bundle
  if (!publicUrls.has(page.url)) continue;
  redirects[page.url] = page.to;
}

const sortedKeys = Object.keys(redirects).sort((a, b) => a.localeCompare(b));

const body = sortedKeys
  .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(redirects[key])},`)
  .join("\n");

const output = `/**
 * Legacy-URL redirect map (auto-generated).
 *
 * DO NOT EDIT BY HAND. Generated by scripts/migration/buildRedirects.ts from
 * scripts/migration/data/classification.json. Maps each PUBLIC legacy docs URL
 * that moved under the new URL scheme to its canonical location; feed it to
 * \`throw redirect(301)\` at the edge. Re-run the builder to regenerate.
 *
 * This map is imported by a route and ships to the browser, so it contains ONLY
 * redirects whose source page is committed at git HEAD. Private/unlaunched
 * product redirects are intentionally excluded so their slugs never ship in the
 * client bundle.
 */

export const LEGACY_REDIRECTS: Record<string, string> = {
${body}
};
`;

const outPath = resolve(dir, "../../src/lib/redirects.generated.ts");
await Bun.write(outPath, output);

// Normalize with biome so the committed output matches repo formatting (long
// entries wrap), keeping the generated file clean under `biome check`
await Bun.$`bunx biome format --write ${outPath}`.quiet();

// biome-ignore lint/suspicious/noConsole: migration script output
console.info(
  `Wrote src/lib/redirects.generated.ts with ${sortedKeys.length} redirects`,
);
