/**
 * Generate the vendored product catalog the docs sidebar reads statuses from.
 *
 * The single source of truth is omni-api. This fetches its public catalog via
 * the shared `@omnidotdev/providers/catalog` client (already public-filtered
 * and normalized server-side) and writes a committed, typed
 * `src/lib/catalog/generated/catalog.ts`. The committed file is what the docs
 * build against, so a build without egress (CI, or an omni-api outage) still
 * ships the last good catalog; it re-runs on every build to keep it fresh.
 *
 * Only the fields the sidebar badges need are emitted (name, status,
 * releaseDate) so the diff stays small. Never hand-edit `catalog.ts`.
 */

import { resolve } from "node:path";

import { fetchPublicCatalog } from "@omnidotdev/providers/catalog";

const outPath = resolve(
  import.meta.dir,
  "../src/lib/catalog/generated/catalog.ts",
);

const catalog = await fetchPublicCatalog(
  process.env.OMNI_API_GRAPHQL_URL
    ? { url: process.env.OMNI_API_GRAPHQL_URL }
    : {},
).catch((error) => {
  // biome-ignore lint/suspicious/noConsole: build script output
  console.warn(
    `[catalog] could not reach omni-api (${error}); keeping committed generated.ts`,
  );
  return null;
});

// Keep the committed catalog when omni-api is unreachable, so a build without
// egress (or during an outage) still ships the last good catalog.
if (!catalog) process.exit(0);

// Deterministic order so regenerations produce stable diffs.
const products = [...catalog.products]
  .sort((a, b) => a.id.localeCompare(b.id))
  .map((p) => ({
    id: p.id,
    name: p.name,
    realm: p.realm,
    status: p.status,
    releaseDate: p.releaseDate,
  }));

const j = (v: unknown) => JSON.stringify(v, null, 2);

const file = `/**
 * Omni product catalog, fetched from omni-api's public GraphQL surface.
 *
 * AUTO-GENERATED by scripts/generateCatalog.ts. Do not edit by hand.
 * Not linted or type-narrowed here; lives under generated/ which biome and
 * knip ignore. Refresh with \`bun run catalog:generate\`.
 */

export interface CatalogProduct {
  id: string;
  name: string;
  realm: string | null;
  /** Lifecycle status, e.g. "active" or "coming_soon". */
  status?: string;
  /** ISO release date. Absent means the product has not launched yet. */
  releaseDate?: string;
}

export const products: CatalogProduct[] = ${j(products)};
`;

await Bun.write(outPath, file);

// biome-ignore lint/suspicious/noConsole: build script output
console.info(`[catalog] Wrote ${products.length} products`);
