/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as SplatIndexRouteImport } from './routes/$/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatIndexRoute = SplatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SplatRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/$/': typeof SplatIndexRoute
}
export interface FileRoutesByTo {
  '/api/search': typeof ApiSearchRoute
  '/$': typeof SplatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/$/': typeof SplatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/api/search' | '/$/'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/search' | '/$'
  id: '__root__' | '/$' | '/api/search' | '/$/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$/': {
      id: '/$/'
      path: '/'
      fullPath: '/$/'
      preLoaderRoute: typeof SplatIndexRouteImport
      parentRoute: typeof SplatRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SplatRouteChildren {
  SplatIndexRoute: typeof SplatIndexRoute
}

const SplatRouteChildren: SplatRouteChildren = {
  SplatIndexRoute: SplatIndexRoute,
}

const SplatRouteWithChildren = SplatRoute._addFileChildren(SplatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
